# Generated by Django 3.1.4 on 2020-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201214_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.TextField(blank=True, null=True),
        ),
    ]
