# Generated by Django 3.1.4 on 2020-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201215_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.TextField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low'),
        ),
    ]
