# Generated by Django 3.1.4 on 2020-12-23 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 22, 30, 53, 699790, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 22, 30, 53, 699814, tzinfo=utc)),
        ),
    ]
