# Generated by Django 3.1.4 on 2020-12-23 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20201223_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
